chore(tooling,deps): update mypy to latest (1.15.0) release (#1209)
* chore(tooling,deps): update mypy to latest version

* chore(tests): fix typo in docstring

* fix(src): raise an exceptoin if there is no parent fork

Fixes mypy 1.15.0 errors:
src/ethereum_test_forks/helpers.py:57: error: Incompatible return value type (got "type | None", expected "type[BaseFork]")  [return-value]
src/ethereum_test_forks/helpers.py:191: error: Incompatible types in assignment (expression has type "type | None", variable has type "type[BaseFork]")  [assignment]

* chore(tooling,tests): fix mypy error

This could be further refactored to remove this fixture entirely; it seems request is never used. No diffs in fixtures with this change.

Fixes mypy 1.15.0 error:
tests/cancun/eip4788_beacon_root/conftest.py:170: error: Incompatible return value type (got "Any | Account", expected "Address")  [return-value]

* chore(fw): improve docstring

* chore(tests): fix typo in docstring

* refactor(tests): help mypy infer Storage type

* docs: update changelog